### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [kapsner/PCRBiasCorrection#11]
Hi. Please note that `multiprocess` is [deprecated since future 1.20.0 (2020-11-03)](https://future.futureverse.org/news/index.html#future-1200) and will soon be defunct:

* https://github.com/kapsner/rBiasCorrection/search?q=multiprocess

**Comment by kapsner** [comment]
Hi @HenrikBengtsson , thanks for this note. This affected the man-files of two functions (`biascorrection` and `on_start`) as well as some unittests. #[c8e8ea1](https://github.com/kapsner/rBiasCorrection/commit/c8e8ea1df3d25c254e90972a0e9664d0b505ad84) should fix this.

**Comment by HenrikBengtsson** [comment]
Thanks. See the search link in my top comment; there are plenty more cases in your test scripts.

**Comment by kapsner** [comment]
> Thanks. See the search link in my top comment; there are plenty more cases in your test scripts.

From this search-link I can see 5 hits, 4 of which are related to the unittests (located under `tests/testthat/...`) and one is in the roxygen-documentation of `R/biascorrection.R`; the related R-code has already been fixed earlier and I just forgot to update the documentation: https://github.com/kapsner/rBiasCorrection/blob/master/R/utils.R#L70

#[c8e8ea1 ](https://github.com/kapsner/rBiasCorrection/commit/c8e8ea1df3d25c254e90972a0e9664d0b505ad84) fixes the 5 remaining hits on the development-branch (I think, GitHub searches only the main-branch so the hits do not yet disappear).

I will prepare a new CRAN release within the next 2 or 3 weeks.
