### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [kapsner/PCRBiasCorrection#4]
Hi

We are preparing the next version of ggplot2 and our tests shows issues with rBiasCorrection. In the next version of ggplot2 `ggsave()` will invisibly return the path of the saved file, which breaks one of your unit tests that expect it to be `NULL`

We plan to submit the next ggplot2 release to CRAN on May 31st

best
Thomas

**Comment by kapsner** [comment]
#7

**Comment by kapsner** [comment]
Closing with #9
